{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.defaultDenyNamespace }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rdash-service.fullname" . }}-default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
