apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://{{ .Values.global.keyvault_name }}.vault.azure.net
      serviceAccountRef:
        name: external-secrets
        namespace: platform
      tenantId: {{ .Values.global.tenant_id | quote }}
